- hosts: all
  become: true

  tasks:
    - name: install the java-1.8.0
      yum:
        name: java-1.8.0
        state: present
    - name: remove java-1.7.0-openjdk package
      yum:
        name: java-1.7.0-openjdk
        state: absent
    - name: download jenkins repo
      shell: "wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat/jenkins.repo && rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key"
    - name: install the jenkins
      yum:
        name: jenkins
        state: present
    - name: Start service jenkins, if not started
      service:
        name: jenkins
        state: started

