- name: install Jdk8
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  become: true

- name: Install git
  yum:
    name: git
    state: present
  become: true

- name: Download Maven Repo
  get_url:
    url: "http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo"
    dest: /etc/yum.repos.d/epel-apache-maven.repo
  become: true

- name: Ansible replace maven-repo
  replace:
    path: /etc/yum.repos.d/epel-apache-maven.repo
    regexp: '\$releasever'
    replace: "6"
  become: true

- name: Install Maven
  yum:
    name: apache-maven
    state: present
  become: true
